on:
  push:
  pull_request:

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.24.3
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
  build:
    name: build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: pnpm install
      - name: build
        run: pnpm run build
  test:
    name: test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: pnpm install
      - name: test
        run: pnpm run test:cov
